name: Test

on:
  push:
      branches:
        - dev
  release:
      branches:
        - dev
      
env:
    PYTHON_VERSION: 3.x

jobs:
  docs:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: LGTM
        run: echo "LGTM" #TODO, uncomment
